In [ ]:
import pandas as pd
from summarytools import dfSummary
from ydata_profiling import ProfileReport
from datetime import datetime

In [16]:
se_data = pd.read_json("../Data/mini_sparkify_event_data.json",lines=True)
se_data['ts'] = pd.to_datetime(se_data['ts'], unit='ms')
se_data['registration'] = pd.to_datetime(se_data['registration'], unit='ms')
se_data.to_csv("../Data/mini_sparkify_event_data.csv", index=False)
se_data.describe()

,ts,sessionId,status,itemInSession,registration,length
count,286500,286500.000000,286500.000000,286500.000000,278154,228108.000000
mean,2018-10-31 03:34:49.810470912,1041.526555,210.054597,114.414213,2018-08-27 08:33:54.085556992,249.117182
min,2018-10-01 00:01:57,1.000000,200.000000,0.000000,2018-03-18 13:44:35,0.783220
25%,2018-10-16 13:35:05.750000128,336.000000,200.000000,27.000000,2018-08-06 02:26:59,199.888530
50%,2018-10-30 20:39:03.500000,1013.000000,200.000000,70.000000,2018-09-11 11:05:02,234.500770
75%,2018-11-15 07:11:04.249999872,1675.000000,200.000000,156.250000,2018-09-23 03:10:36,277.158730
max,2018-12-03 01:11:16,2474.000000,404.000000,1321.000000,2018-11-26 15:49:14,3024.665670
std,NaN,726.776263,31.505078,129.767262,NaN,99.235179

In [17]:
dfSummary(se_data)

In [18]:
profile = ProfileReport(se_data, title="Data Understanding Report", explorative=True)
profile.to_file("../Output/data_understanding/Report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
print(f"shape: {se_data.shape}")
print(f"columns: {se_data.columns.tolist()}")
print(f"data types: {se_data.dtypes.value_counts()}")
print(f"data types: {se_data.dtypes}")
print(f"missing values:\n{se_data.isnull().mean()}")

shape: (286500, 18)
columns: ['ts', 'userId', 'sessionId', 'page', 'auth', 'method', 'status', 'level', 'itemInSession', 'location', 'userAgent', 'lastName', 'firstName', 'registration', 'gender', 'artist', 'song', 'length']
data types: object     12
int64       4
float64     2
Name: count, dtype: int64
data types: ts                 int64
userId            object
sessionId          int64
page              object
auth              object
method            object
status             int64
level             object
itemInSession      int64
location          object
userAgent         object
lastName          object
firstName         object
registration     float64
gender            object
artist            object
song              object
length           float64
dtype: object
missing values:
ts               0.000000
userId           0.000000
sessionId        0.000000
page             0.000000
auth             0.000000
method           0.000000
status           0.000000
level            0.000000
itemInSession    0.000000
location         0.029131
userAgent        0.029131
lastName         0.029131
firstName        0.029131
registration     0.029131
gender           0.029131
artist           0.203812
song             0.203812
length           0.203812
dtype: float64

In [7]:
text_cols = se_data.select_dtypes(include=['object']).columns.tolist()
for col in text_cols:
    print(f"--- {col} ---")
    print(se_data[col].value_counts().head(5))
    print()

--- userId ---
userId
39        9632
          8346
92        7230
140       6880
300011    5732
Name: count, dtype: int64

--- page ---
page
NextSong           228108
Home                14457
Thumbs Up           12551
Add to Playlist      6526
Add Friend           4277
Name: count, dtype: int64

--- auth ---
auth
Logged In     278102
Logged Out      8249
Guest             97
Cancelled         52
Name: count, dtype: int64

--- method ---
method
PUT    261064
GET     25436
Name: count, dtype: int64

--- level ---
level
paid    228162
free     58338
Name: count, dtype: int64

--- location ---
location
Los Angeles-Long Beach-Anaheim, CA       30131
New York-Newark-Jersey City, NY-NJ-PA    23684
Boston-Cambridge-Newton, MA-NH           13873
Houston-The Woodlands-Sugar Land, TX      9499
Charlotte-Concord-Gastonia, NC-SC         7780
Name: count, dtype: int64

--- userAgent ---
userAgent
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"               22751
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4"       19611
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"    18448
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"    17348
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0                                                      16700
Name: count, dtype: int64

--- lastName ---
lastName
Campbell    14060
Reed         9284
Williams     8410
Taylor       7230
Johnson      6106
Name: count, dtype: int64

--- firstName ---
firstName
Payton    9632
Riley     7970
Lucero    6880
Emilia    5732
Emma      5478
Name: count, dtype: int64

--- gender ---
gender
F    154578
M    123576
Name: count, dtype: int64

--- artist ---
artist
Kings Of Leon             1841
Coldplay                  1813
Florence + The Machine    1236
Dwight Yoakam             1135
BjÃÂ¶rk                  1133
Name: count, dtype: int64

--- song ---
song
You're The One                                                         1153
Undo                                                                   1026
Revelry                                                                 854
Sehr kosmisch                                                           728
Horn Concerto No. 4 in E flat K495: II. Romance (Andante cantabile)     641
Name: count, dtype: int64

In [14]:
dfSummary(se_data.groupby('userId').nunique().reset_index())

In [21]:
churned_users = se_data[se_data['page'] == 'Cancellation Confirmation']['userId'].unique()
print(f"Number of churned users: {len(churned_users)}, churn rate: {len(churned_users)/se_data['userId'].nunique():.2%} ")

Number of churned users: 52, churn rate: 23.01%

In [25]:
sum(se_data[se_data['page'] == 'Cancellation Confirmation']['ts'].dt.date >= pd.to_datetime('2018-10-08').date())

45

In [22]:
dfSummary(se_data[se_data['userId'].isin(churned_users)])

In [ ]:
churn_users = se_data[se_data['page'] == 'Cancellation Confirmation'][['userId','ts']].rename(columns={"ts": "cancellation_ts"}).drop_duplicates().copy()
print(churn_users.shape)
se_data_churn = se_data.merge(churn_users, on='userId', how='inner')
se_data_churn['before_cancellation'] = se_data_churn['ts'] < se_data_churn['cancellation_ts']
se_data_churn[~se_data_churn['page'].str.lower().str.contains('cancel')].groupby('userId')['before_cancellation'].agg(['mean','count']).reset_index().describe()
# all events are before cancellation for churned users

(52, 2)

       mean        count
count  52.0    52.000000
mean    1.0   860.769231
std     0.0   852.262378
min     1.0     9.000000
25%     1.0   206.750000
50%     1.0   574.000000
75%     1.0  1152.000000
max     1.0  3601.000000

## Summary of Data Understanding
The dataset contains user activity logs from a music streaming service. Each record represents an event performed by a user, such as playing a song, logging in, or upgrading to a paid account. The dataset includes various attributes related to user demographics, device information, and song details.

### Key Findings:
- The dataset contains logs of user activities with timestamps, user IDs, session IDs, and event types.
- The data has time range from 2018-10-01 to 2018-12-03.
- The data are from 226 users, with a total of 277.4k records.
- 52 users have "Cancellation Confirmation" events, indicating a churn rate of approximately 23%.
- 7 / 52 users churned before 2018-10-08, which may not have enough data for training.

### Questions Required Clarification:
- Definition of "churn"? Currently defined as users who have page event "Cancellation Confirmation", with status 200 as successful cancellation.
- Definition of page events, e.g. Upgrade / Downgrade
- How will this model be used in production? Real-time or batch processing? This will affect formation of cohort for training and evaluation.
- How is the data collected? Any sampling bias?

## Attributes To Be Included in Data Preprocessing and Engineering

* Churn
* Since Registration
* Gender
* Paid Category
* Page event counts
* Device
* Location
* Song stats
* Artist stats
* Session Stats
* Page Stats